### ISSUE TITLE
메타데이터 자동다운로드

### ISSUE THREAD

**Issue by InsanePhin** [laoraid/KartRider.py#2]
#코드
    print("---------메타데이터---------")

    import KartRider
    KartRider.download_meta('metadata')
    KartRider.set_metadatapath('metadata')

    print("----------다운 성공----------")

#오류내용
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File ".\index.py", line 77, in on_ready
    KartRider.download_meta('metadata')
AttributeError: module 'KartRider' has no attribute 'download_meta'

위와 같은 에러가 뜨는데 제가 잘못한걸까요 

InsanePhin#4614

**Comment by laoraid** [comment]
pip에서 업데이트를 해보세요.

`pip install kartrider --upgrade`
